### ISSUE TITLE
Gentlemen, we have a result: what next?

### ISSUE THREAD

**Issue by albertocottica** [albertocottica/communities-network-design#10]
Still waiting for Guy to re-upload some files, but I think the result is robust: disaggregating the influence of nu1 and nu2 was useful. It turns out that nu1 carries almost all the responsibility for bringing the with-onboarding degree distribution back towards the power law form. nu2 seems to have no effect. 

In numbers: 
- correlation coefficient between reject_all and nu1: -0.8263
- correlation coefficient between reject_all and nu2: -0.0034

Running a quick, back-of-the-envelope, no-checks -at-all regression confirms: the coefficient on nu1 is negative, high and strongly significant, that on nu2 is non-significant. R-square is about 0.68.

This is not so intuitive. Directing the first edge towards the newcomer breaks very significant the power law; directing the second edge, after onboarding has worked its magic, has no further effect. 

Anyone has any thoughts?

**Comment by albertocottica** [comment]
Check this out. Here's how nu1 influences the probability of breaking the power law against the control group:
![CDF for various values of nu1](https://cloud.githubusercontent.com/assets/1976806/8025056/05b695d0-0d49-11e5-99a3-738265d0439c.png)

And here's the same thing for nu2:
![CDF for various values of nu2](https://cloud.githubusercontent.com/assets/1976806/8025058/217ae6e0-0d49-11e5-895a-f8470cc4d52c.png)

**Comment by renoust** [comment]
That's clear indeed!

Just to be sure, relaxing the constrain nu_2 <= nu_1 really won't change
anything?

## 

Benjamin

**Comment by albertocottica** [comment]
I do not understand, Ben. There is no constraint. I am simply plotting the cumulative density functions of the p-values for all networks. The convention for naming the variables is:
CDF_ parameterName_parameterValue_pv_all 
These variable were generated by selection: 
`cumulate pv_all if ob == 1 & nu2 == 0.6, generate(CDF_nu2_06_pv_all) equal`
The variable ob (onboarding) is a dummy taking value 1 when onboarding is True. So, the CDF you see happens across all values of nu1. There is no constraint that nu2 <= nu1.

**Comment by renoust** [comment]
Ha, I guess this is what I've understood from this >>>

"""
The first thing we do is to re-run the code as follows. All networks should
be grown to size 2000 to make sure that in-degree spans across 2.5 degrees
of magnitude.
1. no onboarding (control group)
2. nu1 = nu2 = 0
3. nu1 = 0.2, nu2 = 0
4. nu1 = 0.4, nu2 = 0 ... 8 nu1 = 0.4, nu2 = 0 etc.

"""

So my misunderstanding is the same from day 0 then.
So let me just forget it, and make nu1 and nu2 vary in the [0..1] space
independently.

## 

Benjamin

**Comment by albertocottica** [comment]
I am trying to save you computation... but nu1 == 0 is a special case. If "onboarding does not work", it does not matter how chatty the community is, nothing will happen. So, there is really no reason to run the six simulations for six values of nu2 if nu1 is equal to 0. In that case, exactly two edges will be generated at each run; one allocated by preferential attachment, the other targeting the newcomer. 

When nu1 > 0 it's another matter. In that case, with probability nu1 an edge will go out of the newcomer, and will be reciprocated with probability nu2. Now the value of nu2 does make a difference. 

Makes sense?

**Comment by renoust** [comment]
Ah I see, reading too fast then. Yes makes sense!
In a very geek way, it's simpler for me to execute all cases rather than
detailing this case, it's well... it's square :) so I've inferred that it
was... half a square :)
I'm making the mistake for some time now :), sbdy should have stopped me :)
well it's a good lesson...
Beer's on me then!

## 

Benjamin

**Comment by albertocottica** [comment]
Well, you are welcome to execute all cases. But you are _free_ to drop those 5 extra runs without loss of generality. My job is to stay on top of interpretation of results... :-)

**Comment by albertocottica** [comment]
Closed
