### ISSUE TITLE
VIsualizations of degree distributions: how-to

### ISSUE THREAD

**Issue by albertocottica** [albertocottica/communities-network-design#13]
@renoust, you asked to share the method to draw degree distributions. I uploaded some code:

https://github.com/albertocottica/communities-network-design/blob/master/Code/drawDegreeDistributions.py

An interesting question is how to aggregate across different networks. I think I would do it this way (pseudocode):

```
def draw (data):
  # draw the degree distribution using the code above or some other
nu1Values = [0,1] 
nu2Values = [0,1]
for nu1 in nu1Values:
  for nu2 in nu2Values:
    # generate 100 degree distributions
    aggregatedDistro = []
    for deg in range (degreeMax):
      agg = # the sum all items of value deg across all 100 distributions, divided by 100
      aggregatedDistro.append(agg)
    draw (aggregatedDistro)
```

Makes sense? Who can do this?

**Comment by guywiz** [comment]
Hmm ... When plotting a histogram, although we often report on the actual number of observations (nb of nodes having degree k in our case), you may well report observed frequencies (so the integral of the histogram seen as a discrete probability distribution sums up to 1).

So, when dealing with data coming from multiple datasets (all cming from the same population), I would simply collect all data into a single dataset and plot the histogram using frequencies.

?

**Comment by albertocottica** [comment]
Yes, you are right, that will work too.

**Comment by renoust** [comment]
Thanks Alberto, I think this can be included in the root code automagically
:)
Btw, @Guywiz, we'd need the last revision of the code to be uploaded if
possible, right now only one generation is executed.
I think we should all have hands on the code, but the core part should more
or less remain the same now.

Warning: right now, we do not yet generate 100 onboarding models, but only
one.

Second reflection on drawing graphs:
We are not shocked when viewing Erdos-Renyi instances even without
cumulating over multiple generations despite their random nature, I think
nothing should prevent us from visualizing them, as long as we state this
is "one" instance... Also, with a number of nodes large enough, variations
between 2 generations should be rather low.

## 

Benjamin

**Comment by albertocottica** [comment]
@renoust yes, that is a way out too. However, it does introduce a weakness, which is not there in ER graphs because they are very well understood. Even just generating 4 or 5, and checking that they have a similar in-degree distributions before we only display one would be useful.

**Comment by guywiz** [comment]
Hmm ... I am not sure I want to modify the code the way you suggest. Simply because the OnBoarding class was designed to be used by the PowerlawFitting class and, most importantly, to comply with parallel execution.

You can repeatedly create a new instance of the OnBoarding class to generate multiple graphs. And if you don't like the idea of throwing away a class and instantiating a brand new one, then just reset the self.graph variable:
self.graph = networkx.MultiDiGraph()
and then run the generate() method.

**Comment by albertocottica** [comment]
This is beyond me. But actually yes, at the moment, for each couple nu1 / nu2 Guy's code does generate 100 networks and extracts their degree distributions. Only, these distributions are not saved as csv files, and instead are simply used as input for the goodness-of-fit statistical tests.

**Comment by renoust** [comment]
@albertocottica: yes can do, it will be useful at least for your thesis
manuscript, anyway
@guywiz: this is parametrizable, I have parametrized my own version, so I
do not fit all
the time, when it's not useful, also I have parametrized the parallel
execution as well.
Please update the code if you want I can include all the parameters
@albertocottica: looking at the code from the git repository I don't see
where this 100
generation happens?!
I think I don't have the right code

## 

Benjamin

**Comment by albertocottica** [comment]
@renoust if you take any of the Fitting_statistics files you see the fitting done with 100 networks with the same generating parameters. Example:

https://github.com/albertocottica/communities-network-design/blob/master/Datasets/FittingData/Fitting_statistics_2000_1_False_1.0_2500.csv

**Comment by albertocottica** [comment]
Sorry, I linked the one file that was different. I mean this: 

https://github.com/albertocottica/communities-network-design/blob/master/Datasets/FittingData/Fitting_statistics_2000_1_True_0.0_0.0_1.0_2500.csv

**Comment by renoust** [comment]
Ah thanks, ok, I was based on a reading of the code (after the
parallelization).

So @guywiz, you put 100 parallel workers to generate a 100 distributions
then,
and each of the different one has its own call to generate()

I can make the nxgraph part of the returns then, as a post process, we can
think
of comparing/merging/visualizing the generated models.

## 

Benjamin

**Comment by guywiz** [comment]
Once the generatemethod has done its work, the generated graph is in the self.graph variable.

**Comment by albertocottica** [comment]
Closed
