### ISSUE TITLE
Re-generate control group networks with N = 2000

### ISSUE THREAD

**Issue by albertocottica** [albertocottica/communities-network-design#14]
I am not fully convinced that the data I am working with relative to the control group correspond to networks with N = 2000. Certainly there seems to be no control group here:

https://github.com/albertocottica/communities-network-design/tree/master/Datasets/FittingData

While I don't expect different results, Guy: could you re-generate the data? 100 networks only, with onboarding = False. Thanks!

**Comment by guywiz** [comment]
We'll re-run the code in/from Brighton ... :-)

**Comment by albertocottica** [comment]
Done
