### ISSUE TITLE
Missing run for nu1 = 1.0, nu2 = 0.0

### ISSUE THREAD

**Issue by albertocottica** [albertocottica/communities-network-design#9]
Unless I am mistaken... @guywiz, can you check in your files and upload the missing one? It should be called:

Fitting_statistics_2000_1_True_1.0_0.0_1.0_2500.csv

**Comment by guywiz** [comment]
Gosh, I had overlokked it. It is now on the git.

**Comment by albertocottica** [comment]
Closed
